### ISSUE TITLE
Regarding the process_primitive function, which handle should I choose?

### ISSUE THREAD

**Issue by jiaweiguan** [davisyoshida/qax#4]
This is a great job, but I have a few questions. I have limited abilities, and my expression may be lacking. Regarding the process_primitive function, which handle should I choose? 
Are the custom handlers like convert_element_type, transpose, and others defined in Lorax?
From my understanding, it seems that I can directly use the default_handler because it appears to be the implementation of materialize_handler, which is the LoraWeight.materialize method in Lorax. 

![image](https://github.com/davisyoshida/qax/assets/32994356/fe5ca495-7a87-4a64-b3b9-5a07be55a7ed)

**Comment by davisyoshida** [comment]
I'm not sure I 100% understand the question, but the handlers for things like `convert_element_type` in Lorax can be seen here: https://github.com/davisyoshida/lorax/blob/28a839265e240cd4a8d3f41605c6f2182d2168fb/lorax/transform.py#L155

**Comment by jiaweiguan** [comment]
I know it. But it is not my question. It's possible that my understanding of the code is not sufficient, and I need some time to fully comprehend it and express it accurately.

**Comment by davisyoshida** [comment]
Can you try to explain a bit more what you want to do?
