### ISSUE TITLE
Jax version requirement

### ISSUE THREAD

**Issue by bminixhofer** [davisyoshida/qax#6]
Hi,

I've seen in 3a3e510 that the minimum Jax version was bumped to >=0.4.24.
I suppose this is necessary to run this library (and by extension Lorax)? I am running Jax on Google Cloud TPUs with default Jax version 0.4.13 and I'd love to use your libraries there.

Thanks for any help!

**Comment by davisyoshida** [comment]
The easiest thing to do would probably be install qax==0.3.0. Does that work for you?

**Comment by bminixhofer** [comment]
Hi, I ended up setting up a conda env with a more recent Jax version. I was a bit cautious about changing the Jax version of the default image but it works just fine!

**Comment by davisyoshida** [comment]
Great! Let me know if you have any issues. I'd love to help.
